// vue-exports/videos-v2/components/V2Cell.vue
<template>
  <div
    :style="{
      width: `${width}px`,
      minWidth: `${width}px`,
      maxWidth: `${width}px`,
      display: 'flex',
      alignItems: 'center',
      justifyContent: align === 'center' ? 'center' : 'flex-start',
      overflow: 'hidden',
    }"
  >
    <slot />
  </div>
</template>

<script setup lang="ts">
interface Props {
  width: number
  align?: 'left' | 'center'
}

withDefaults(defineProps<Props>(), {
  align: 'left',
})
</script>

// src/app/components/video-table-v2/V2Cell.tsx
/**
 * V2Cell — fixed-width container for a single column slot.
 * Aligns children either left (default) or center.
 */
import React from "react";

interface V2CellProps {
  width:   number;
  align?:  "left" | "center";
  children: React.ReactNode;
}

export function V2Cell({ width, align = "left", children }: V2CellProps) {
  return (
    <div
      style={{
        width:          width,
        minWidth:       width,
        maxWidth:       width,
        display:        "flex",
        alignItems:     "center",
        justifyContent: align === "center" ? "center" : "flex-start",
        overflow:       "hidden",
      }}
    >
      {children}
    </div>
  );
}
